[geeknews]
title = "GeekNews"
url = "https://news.hada.io/new"
entrySelector = ".topic"
titleSelector = "td.topictitle > a > h1"
linkSelector = "td.topictitle > a"
contentSelector = "body > main > article > table > tbody > tr.topictitle > a > h1"

[velog]
title = "velog"
url = "https://velog.io"
entrySelector = ".sc-dVhcbM"
titleSelector = "h4"
linkSelector = ".sc-fMiknA"
contentSelector = ".description-wrapper"

[kakaotech]
title = "kakaotech"
url = "https://tech.kakaoenterprise.com/"
entrySelector = ".thumb"
titleSelector = ".title"
linkSelector = ".summary"
