[geeknews]
title = "GeekNews"
url = "https://news.hada.io/new"
entrySelector = "body > main > article > table > tbody > tr"
titleSelector = "td.topictitle > h1"
linkSelector = "td.topictitle > td > a"
