[geeknews]
title = "GeekNews"
url = "https://news.hada.io/new"
entrySelector = "body > main > article > table > tbody"
titleSelector = "tr.topic > td.topictitle > a > h1"
linkSelector = "tr.topic > td.topictitle > a"
