[geeknews]
title = "GeekNews"
url = "https://news.hada.io/new"
entrySelector = ".topic"
titleSelector = "td.topictitle > a > h1"
linkSelector = "td.topictitle > a"
contentSelector = "body > main > article > table > tbody > tr.topictitle > a > h1"
